Se agregan conceptos para usar en tesoreria
udistrital/cuentas_contables_crud pull request #65
Opened 2022-01-20 16:08 UTC by diagutierrezro

https://github.com/udistrital/tesoreria_cliente/issues/145

2022-01-25 00:06 UTC, AlexFBP requested changes
En general bien
- Para las funciones, agregar al menos las defer.func para errores sin manejar, sobretodo donde haya:
  - Lógica de negocio
  - Creación de entidades
 Referencia: tesoreria_mid: [controller](https://github.com/udistrital/tesoreria_mid/blob/fcbd37d8cd99bb902396d31ff343832d6a7511d8/controllers/cuenta_bancaria_banco.go#L30) - [helper](https://github.com/udistrital/tesoreria_mid/blob/fcbd37d8cd99bb902396d31ff343832d6a7511d8/helpers/cuenta_bancaria_banco.go#L16-L17)
- Para los controller, referencia: [documentacion de Beego](https://beego.vip/docs/advantage/docs.md) ([cache](https://webcache.googleusercontent.com/search?q=cache:CHenz9rEmF4J:https://beego.vip/docs/advantage/docs.md+&cd=2&hl=es-419&ct=clnk&gl=co))

2022-01-25 16:21 UTC, diagutierrezro commented on controllers/conceptos.go
> +// @Success 200 {int} models.Conceptos.Id
Se realizan varios ajustes a los comentarios para el swagger

2022-01-26 03:07 UTC, diagutierrezro commented on managers/conceptos.manager.go
> +		return
Ya que err no se usará mas adelante se puede eliminar

2022-01-26 16:16 UTC, diagutierrezro commented on managers/conceptos.manager.go
> +	}
Se agrega variable para poder dejar solo el =

2022-01-26 16:19 UTC, diagutierrezro commented on managers/conceptos.manager.go
> +	nodesDataIndexed = make(map[string]*models.NodoArbolConceptos)
Se mantiene ya que al eliminarlo arroja error por conversión de interface

2022-01-27 00:50 UTC, AlexFBP requested changes
Algunos ajustes finales a los controladores y quedaría...

2022-01-27 21:19 UTC, AlexFBP approved these changes

2022-01-27 21:19 UTC, merged