Feature/porcentajes retencion
udistrital/cuentas_contables_crud pull request #77
Opened 2022-05-17 11:34 UTC by salcedogeiner

https://github.com/udistrital/contabilidad_cliente/issues/141

2022-05-18 06:32 UTC, AlexFBP requested changes
Bien en general. La mayoría de comentarios dejados son menores

2022-05-18 06:32 UTC, AlexFBP commented on controllers/tipo_retencion.go
> +	"go.mongodb.org/mongo-driver/mongo"
(En general - comentario menor) Tratar de dejar los import separados (agrupados?) según:
1. paquetes core, oficiales de Go ("net", "fmt", "url", entre otros)
2. paquetes fuera de github/udistrital
3. paquetes github/udistrital

Algo así (se puede aplicar este _suggested change_ via web)
```suggestion
	"github.com/astaxie/beego"
	"go.mongodb.org/mongo-driver/mongo"

	"github.com/udistrital/cuentas_contables_crud/helpers"
	"github.com/udistrital/cuentas_contables_crud/managers"
	"github.com/udistrital/cuentas_contables_crud/models"
```

2022-05-18 06:32 UTC, AlexFBP commented on controllers/tipo_retencion.go
> +	err := c.crudManager.GetAllDocuments(filter, -1, 0, models.TipoRetencionCollection, func(curr *mongo.Cursor) {
Se recomienda agregar soporte a paginación, que se pueda especificar
- o bien el limit y el offset
- o bien la pagina y la cantidad de resultados (e internamente calcular el limit/offset a ser pasados a `GetAllDocuments`

Y que el `-1`, `0` del comportamiento actual, queden como valores por defecto en caso de no especificarse alguno de los dos

2022-05-18 06:32 UTC, AlexFBP commented on db/migration.manager.go
> +	dbPort := "27017"
Traer este valor de una variable de entorno. En `conf/app.conf` agregar la siguiente línea:
```ini
mongo_port = ${CUENTAS_CONTABLES_CRUD_DB_PORT||27017}
```
Lo anterior permite tomar el 27017 como valor por defecto en caso de no estar `CUENTAS_CONTABLES_CRUD_DB_PORT` declarada, y también que se pueda aplicar el siguiente _suggested change_:
```suggestion
	dbPort := beego.AppConfig.String("mongo_port")
```

2022-05-18 06:32 UTC, AlexFBP commented on migrations/20220515_tipo_cuenta_contable.go
> +	"go.mongodb.org/mongo-driver/mongo"
(_suggested change_ menor, mas que todo por "convención")
```suggestion
	migrate "github.com/xakep666/mongo-migrate"
	"go.mongodb.org/mongo-driver/mongo"

	"github.com/udistrital/cuentas_contables_crud/models"
```

2022-05-18 06:32 UTC, AlexFBP commented on migrations/20220516_tipo_retencion.go
> +	"go.mongodb.org/mongo-driver/mongo"
(_suggested change_ menor, mas que todo por "convención")
```suggestion
	migrate "github.com/xakep666/mongo-migrate"
	"go.mongodb.org/mongo-driver/mongo"

	"github.com/udistrital/cuentas_contables_crud/models"
```

2022-05-18 06:32 UTC, AlexFBP commented on migrations/20220516_tipo_retencion.go
> +			Label: "19",
Estos id ... :thinking: ... Los podríamos tomar-de/centralizar-en un bloque de constantes al comienzo de este archivo? (Para de paso poder ser usadas en otros lados en caso de repetirse, y facilitar el cambio a futuro de ser necesario)
```golang
const (
  IdTipoRetencionUno = "5"
  IdTipoRetencionDos = "19"
)
```
Inclusive, se podría crear un archivo "constantes.go" en la misma carpeta de este, que empiece con "package migrations"

----------------------------------------

Por otro lado, [en teoría no deberían correrse migraciones en producción](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/beego_migrations.md#33--consistencia-de-la-migraci%C3%B3n), lo cual se está contemplando desde ya en la lógica, las posibles implicaciones que esto tenga deberán documentarse... :grimacing: 
Hay alguna forma de hacer que las migraciones se corran como una opción de linea de comandos? Para, digamos, poder llamarlas en los steps migrate/rollback de Drone, de manera similar que se hace con las que tienen DB Postgres? :thinking:

2022-05-19 01:08 UTC, salcedogeiner commented on controllers/tipo_retencion.go
> +	err := c.crudManager.GetAllDocuments(filter, -1, 0, models.TipoRetencionCollection, func(curr *mongo.Cursor) {
resuelto

2022-05-19 04:48 UTC, AlexFBP requested changes
Un ajuste menor adicional y quedaría :ok_hand: . Para que los _suggested changes_ dejados a los  `controllers/...` tengan efecto, aplicarlos y luego actualizar los swagger, bien sea con `bee run -downdoc=true -gendoc=true` o con `bee generate docs`.

2022-05-19 04:48 UTC, AlexFBP commented on controllers/detalle_cuenta_contable.go
> +// @Param	offset	query	string	false	"Start position of result set. Must be an integer"
```suggestion
// @Param	limit	query	int	false	"Limit the size of result set. Must be an integer"
// @Param	offset	query	int	false	"Start position of result set. Must be an integer"
```

2022-05-19 04:48 UTC, AlexFBP commented on controllers/naturaleza_cuenta_contable.go
> +// @Param	offset	query	string	false	"Start position of result set. Must be an integer"
```suggestion
// @Param	limit	query	int	false	"Limit the size of result set. Must be an integer"
// @Param	offset	query	int	false	"Start position of result set. Must be an integer"
```

2022-05-19 04:48 UTC, AlexFBP commented on controllers/tipo_cuenta.go
> +// @Param	offset	query	string	false	"Start position of result set. Must be an integer"
```suggestion
// @Param	limit	query	int	false	"Limit the size of result set. Must be an integer"
// @Param	offset	query	int	false	"Start position of result set. Must be an integer"
```

2022-05-19 04:48 UTC, AlexFBP commented on controllers/tipo_moneda.go
> +// @Param	offset	query	string	false	"Start position of result set. Must be an integer"
```suggestion
// @Param	limit	query	int	false	"Limit the size of result set. Must be an integer"
// @Param	offset	query	int	false	"Start position of result set. Must be an integer"
```

2022-05-19 04:48 UTC, AlexFBP commented on controllers/tipo_retencion.go
> +// @Param	offset	query	string	false	"Start position of result set. Must be an integer"
```suggestion
// @Param	limit	query	int	false	"Limit the size of result set. Must be an integer"
// @Param	offset	query	int	false	"Start position of result set. Must be an integer"
```

2022-05-19 04:48 UTC, AlexFBP commented on conf/app.conf
> +mongo_port = ${CUENTAS_CONTABLES_CRUD_DB_PORT}
(En general) Dejar vacía, sin espacios ni nada, la última línea en archivos de texto
```suggestion
mongo_port = ${CUENTAS_CONTABLES_CRUD_DB_PORT}

```

2022-05-19 04:48 UTC, AlexFBP commented on migrations/20220516_tipo_retencion.go
> +			Label: "19",
Hecho, mencionado en #78

2022-05-20 00:59 UTC, AlexFBP approved these changes

2022-05-20 01:00 UTC, merged